import type { Metadata } from "next";
import { Geist, Geist_Mono, Alegreya } from "next/font/google";
import "./globals.css";
import NavBar from "@/shared/components/navigation/NavBar";
import ReactQueryProvider from "@/shared/providers/ReactQueryProvider";
import Footer from "@/shared/components/footer/Footer";
import LenisProvider from "@/shared/components/ui/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-alegreya",
});

export const metadata: Metadata = {
  title: "Vinyl Record Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${alegreya.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <ReactQueryProvider>
          <LenisProvider />
          <NavBar />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
